### ISSUE TITLE
Update links to example scripts in the docs

### ISSUE THREAD

**Issue by kevinyamauchi** [napari-threedee/napari-threedee#111]
In #104, we moved the example scripts to the `docs` folder and created a gallery. Some of our "how-to's" point to those scripts, so we should update the links accordingly.

**Comment by GenevieveBuckley** [comment]
I didn't see any links in the how-to guides (or anywhere else) pointing to any of the examples scripts. Which ones do you mean?

**Comment by kevinyamauchi** [comment]
Sorry, @GenevieveBuckley , I should have been more clear in the initial post. For example [here](https://napari-threedee.github.io/how_to/point_manipulator/) under step 1. I think we should point  that link to the new gallery pages (for the "how to's" that have a corresponding gallery page).

**Comment by psobolewskiPhD** [comment]
I think this can be closed? All of the how-to now have links to the correct script and instructions how to use the script.
