### ISSUE TITLE
Update mkdocs & mkdocs-gallery versions

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari-threedee/napari-threedee#113]
**The mkdocs-gallery version 0.7.7 is available now! Someone can make a PR for this issue.**

~~We're waiting for the next `mkdocs-gallery` release to come out before we can update these versions. See https://github.com/smarie/mkdocs-gallery/releases (we need higher than 0.7.6)~~

**Details:**
When we added the napari-threedee examples gallery https://github.com/napari-threedee/napari-threedee/pull/104, we had to pin `mkdocs==1.2.4` because of this bug in mkdocs-gallery https://github.com/smarie/mkdocs-gallery/issues/57.

Since then, PR https://github.com/smarie/mkdocs-gallery/pull/60 fixed issue https://github.com/smarie/mkdocs-gallery/issues/57. So, when the next mkdocs-gallery release comes out we can require `mkdocs-gallery>0.7.6` and unpin `mkdocs`.

Like this, in `setup.cfg`
```
[options.extras_require]
dev = 
	mkdocs
	mkdocs-gallery>0.7.6
        ...
```

**Comment by smarie** [comment]
0.7.7 is out ! https://smarie.github.io/mkdocs-gallery/changelog/

**Comment by kevinyamauchi** [comment]
Cool! Thanks everyone! I will try and update

**Comment by GenevieveBuckley** [comment]
Looks great!

**Comment by smarie** [comment]
Gorgeous ! Great job !
