### ISSUE TITLE
Enhancement request: use 3 colors for the RenderPlaneManipulator balls

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#153]
Currently, the RenderPlaneManipulator has 2 green balls and one purple one. When trying to explain--or learn--it's hard to tell which of the green balls is which. If one used a 3rd color, it would be much simpler a it would be more distinct.

**Comment by psobolewskiPhD** [comment]
So I can tell the color of the balls is connected to the axes, but it's a bit of a mystery how to change them to make them unique...

**Comment by alisterburt** [comment]
this class is the key:

https://github.com/napari-threedee/napari-threedee/blob/43a3a8205e5c4af8bef2db7d2ea29a6377790faf/src/napari_threedee/_backend/manipulator/axis_model.py#L7-L12

translators and rotators both contain axes and the colors depend on the axis that you are translating along or rotating around - you're right that these are tightly coupled right now but changing them should be possible by modifying that model directly at whatever moment :-)

**Comment by psobolewskiPhD** [comment]
Ok, I'm getting it. The ball colors match the axis colors, so the orange ball rotates around the orange axis.
The one green ball is a green axis rotator, around the green axis, the other is the green axis translator, along the green axis.
Makes sense now.
So really the translator handle maybe could be a diamond or something to make it more distinct.

**Comment by alisterburt** [comment]
Sure yeah that could be a good way to distinguish it!

**Comment by psobolewskiPhD** [comment]
So the handles are vispy markers! I thought I could just use `.symbol = "diamond"` but it didn't work. I'll poke around some more, maybe it's not too hard to make the translator handles distinct from the rotator ones.

**Comment by psobolewskiPhD** [comment]
I got it working!
