### ISSUE TITLE
Question/Enhancement: why only 1 plane rotator for the render plane manipulator, rather than pitch & yaw?

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#164]
The render plane manipulator has 3 balls:
- the translator which moves the plane along it's normal
- the rotator which changes the plane normal
- and a 3rd one which rotates the manipulator so that the rotation can be performed in a different orientation

This works, but takes some getting used to.
It seems like it would be more natural to have:
- the translator which moves the plane along it's normal -- unchanged
- one rotator which changes the plane normal in 1 orthogonal orientation, call it pitch
- second rotator which changes the plane normal in 2 orthogonal orientation, call it roll
- optionally, the final ball could be preserved to rotate the manipulator so that the rotations can be performed in a different orientation

cc: @alisterburt I think you implemented the basics of these?

Looking at the code, it feels like there are only two functions: translator hooked to plane position and rotator hooked to plane normal, but there clearly is a 3rd (unnamed?) function, which just rotates the manipulator.
Edit: oh I get it, the 3rd ball doesn't rotate the manipulator, it rotates the plane around the normal, so **it's yaw**. It just looks like it's the manipulator rotating! The color thing (https://github.com/napari-threedee/napari-threedee/issues/153) doesn't help, but I think I get it now. I will make a trial PR this evening.

**Comment by alisterburt** [comment]
wasn't a super active decision, just felt like more clutter... I think you can get the behaviour you want by changing:

https://github.com/napari-threedee/napari-threedee/blob/43a3a8205e5c4af8bef2db7d2ea29a6377790faf/src/napari_threedee/manipulators/render_plane_manipulator.py#L12

to        
```
 super().__init__(viewer, layer, rotator_axes='xyz', translator_axes='z')
```

**Comment by psobolewskiPhD** [comment]
Yup, that's what I figured out. Thanks for confirming. I'll play around with it. Feels pretty intuitive.
As is it makes sense once you get it, but I think at first it's a bit odd.

**Comment by alisterburt** [comment]
Yeah, in general I don't know how intuitive 3D manipulation like this can be... I'm all ears for any tips you've got from other softwares but my general take is it's all okay until you're only interacting with one component of a scene 😆
