### ISSUE TITLE
Bug: the click targets of manipulator handles are larger than handle graphic

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#173]
- tested with 0.0.12-16
- layer and render plane manipulators

The effect is more pronounced with higher zoom, but basically the click target exceeds the handle graphic. So sometimes you want to rotate the view, but instead you are grabbing a handle and manipulating your plane (or layer).
I thought it might be related to the layer -> world change, but it happens in previous versions, as far back as 0.0.12 before any of the recent changes.

**Comment by psobolewskiPhD** [comment]
Not sure if related, but at higher zooms a line sticks out of the translator:
<img width="1198" alt="image" src="https://github.com/napari-threedee/napari-threedee/assets/76622105/a79d910d-ac25-4ef1-a282-5da84e901b81">

(this also happens with 0.0.12 and 0.0.16)

**Comment by kevinyamauchi** [comment]
Thanks for the bug report! This might be related to some of the point size issues we've seen in napari in the past. I think at high zooms, the point size isn't rendered properly. I can take a closer took later.

**Comment by psobolewskiPhD** [comment]
Argh, this could be the macOS GL marker size limitation
https://github.com/vispy/vispy/issues/2078
Maybe the marker is drawn smaller than it really is on my screen.

**Comment by psobolewskiPhD** [comment]
I thought this might be something with `scale`, but it happens with (1, 1, 1) scale layers.
It's not the marker size issue on macOS, because I can make vanilla napari points size 10 and the interaction target is just a bit larger, while for the handles it's ~3X larger. So something else is off.

**Comment by alisterburt** [comment]
https://github.com/napari-threedee/napari-threedee/blob/main/src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py

The drag manager from click method in the manipulator backend above calls a select sphere from click data function

https://github.com/napari-threedee/napari-threedee/blob/main/src/napari_threedee/utils/selection_utils.py

There's an arithmetic error on line 182, it should be ((handle sizes - 1) / 2)

Sorry for lack of formatting, on mobile - hope that helps?!

**Comment by psobolewskiPhD** [comment]
Yeah! Helps a lot. 
Of course, when zooming then hit:
https://github.com/vispy/vispy/issues/2078
But your suggestion fixes the behavior otherwise.
