### ISSUE TITLE
[bug] when translating a render plane, the manipulator slides along the plane

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#191]
This is pretty minor, but if you translate a render plane using the translator, as the plane moves the manipulator.
(no scaling involved)

https://github.com/napari-threedee/napari-threedee/assets/76622105/07c3b9ca-2968-41cc-9269-5264c1ff2b11

Not sure if this was always an issue or if it's from the recent flurry of PR.
I will try to track it down and fix.

**Comment by psobolewskiPhD** [comment]
Feels like the position should be clipped to the layer extent at the very least, or maintained in the same relative location in the plane.

**Comment by alisterburt** [comment]
I think this is a recently introduced issue - something to do with the handling of transforms looks off

**Comment by psobolewskiPhD** [comment]
Hmm, I went back before the data to world coords PR and it still happens, so it might be long standing.

In a sense it's not wrong -- the slicing plane is infinitely large and as we advance it along the normal a different part of the plane is passing through the data, showing it. So the origin of the manipulator, if advanced along the normal, will go out of a finite volume eventually.

So the question is what is the correct behavior?
Playing with shift-drag in vanilla napari, the plane.position is always within the layer bounding box.
If you add a manipulator you will see slide around the edges of a volume as you move the plane, but unable to leave, because napari is preventing plane.position from leaving the extent. 

But if I use the manipulator, as mentioned above, then plane.position happily exceeds the layer bounding box, so in fact napari doesn't limit what you can set. In fact, we could consider this a napari bug, because you can do `layer.plane.position = (z, y, x)` and enter values outside the bounding box.  Maybe it shouldn't be possible to set the position of a plane outside the bounding box? Right now the `Plane` class doesn't have a setter for position:
https://github.com/napari/napari/blob/7b46a844634ef4f88d5f434a0be11da53df28bea/napari/layers/utils/plane.py#L23
(there is just validation that it's a tuple of float)

Anyhow we could do the same logic as napari and limit the change in origin to extent (we could import the function itself I think or bring it in, it's quite simple)

The other option would be to try to keep the relative position of the manipulator in the visualized part of the plane the same. This might look better? But then the origin and the translator will never actually move along the normal, so it could be confusing? while at the moment, they always do.

So right now I lean to just having self.origin be limited to the bounding box, like napari limits plane.position. This would be rather simple to implement.

**Comment by alisterburt** [comment]
I think I misunderstood the problem in the original report: I thought the origin started inside the volume and finished outside the volume but is it actually starting and ending outside?

If it's limited to the bounding box in napari and feels natural there I'd say we should do the same with this manipulator🙂

**Comment by psobolewskiPhD** [comment]
Origin is starting inside the volume, middle-middle essentially.
origin = plane.position
But then as you drag the translator origin moves along the normal, so for an oblique plane it can move outside the bounding box and plane.position is also set outside the bounding box.
If you just drag a plane using shift-drag in napari instead, plane.position is limited to the bounding box.
Here's the function:
https://github.com/napari/napari/blob/7b46a844634ef4f88d5f434a0be11da53df28bea/napari/utils/geometry.py#L195

**Comment by psobolewskiPhD** [comment]
In threedee the other function `point_in_bounding_box` is implemented (not sure where it was first, here or napari):
https://github.com/napari-threedee/napari-threedee/blob/d6c504acf8b0e4e395ec0b5f35516fe0dff58f16/src/napari_threedee/utils/geometry.py#L77

So could add the clamp function there too. Or import from napari.

**Comment by alisterburt** [comment]
Using the threedee function sounds excellent! I don't see exactly why the plane being oblique is relevant to whether it can end up outside the box but you've been playing and seem to understand what's going on better than me :)

**Comment by psobolewskiPhD** [comment]
Of course you are correct! But with a x, y, or z plane when the origin/position goes outside the bounding box, then there is nothing visualized and it's an edge case (🥁) but with an oblique plane it happens all the time while still visualizing.

**Comment by psobolewskiPhD** [comment]
So as far as I can tell all the *manipulator* dragging happens on the backend:
https://github.com/napari-threedee/napari-threedee/blob/8fbe1631d3f16c90e33560ed053d5ea2045c94fb/src/napari_threedee/_backend/manipulator/napari_manipulator_backend.py#L128-L134

So all the manipulators behave the same in this regard. Clamping here works as expected for the render plane, but of course clamping *doesn't make sense* for points or layer manipulators. It's actively the opposite of what they are meant to do -- especially the layer one.
So outside a much larger refactor, I'm not sure where is an easy way to do this.

In the RenderPlaneManipulator class, the origin info is used to set the plane position, but that doesn't help with the issue.
