### ISSUE TITLE
[Bug] If two plane annotators result in duplicate points

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#194]
If you create two image layers and two points layers, and create a PointAnnotator for each pair of image:points layer, then no matter which image layer is selected, the alt-click keybinding puts the points on both layers, rather than just using the selected layer.

![image](https://github.com/napari-threedee/napari-threedee/assets/76622105/ffe1e86b-5777-435e-8181-340eff832f8f)

Workaround: disable one before switching annotations by setting `enabled=False`

**Comment by alisterburt** [comment]
Interesting, definitely didn't account for this use case when building!

The mechanism for solving it that pops into my head is to attach/detach the callback from the annotater when layer selection changes

**Comment by alisterburt** [comment]
Or as you suggest, enable/disable the annotator on layer selection change

**Comment by kevinyamauchi** [comment]
> Or as you suggest, enable/disable the annotator on layer selection change

I think this is the best way to go. I think this makes it more obvious what is happening. Enabling/disabling the callback (or adding some flag) would also work, but I think it's a bit hidden from the user and might be confusing.

**Comment by psobolewskiPhD** [comment]
So right now selected layer plays no role.
layer `plane` is connected to the Points layer (using widget)
Left 4 points were with `plane` selected, the 2 on the right with `nuclei` selected:
<img width="1198" alt="image" src="https://github.com/napari-threedee/napari-threedee/assets/76622105/0ef934e3-7a7e-4043-816d-f5a8329ac335">

Maybe a check for selection here would suffice? I'll try it 😄 
https://github.com/napari-threedee/napari-threedee/blob/65d1b012ddbd1442d1e2bb38e032adc01d09b07a/src/napari_threedee/annotators/points/annotator.py#L29-L37
