### ISSUE TITLE
[bug] setting handle_size < 5 makes manipulators impossible to interact with

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#196]
Since https://github.com/napari-threedee/napari-threedee/pull/168 manipulators use world coordinates.
It's common in various microscopy to have layers with scale well less than 1, so then a handle_size of 10 world coordinates is gigantic.
In https://github.com/napari-threedee/napari-threedee/pull/174 handle_size was made a property so it could be changed.
Currently, setting handle_size <5 makes the manipulator impossible to interact with.
It's due to this line:
https://github.com/napari-threedee/napari-threedee/blob/9538a21fe0f69bd4d92a66b31fbb0062581e2ac6/src/napari_threedee/utils/selection_utils.py#L180-L182

For numbers less than 5, we get values near zero or worse.
I adjusted the parens here:
https://github.com/napari-threedee/napari-threedee/pull/185/files
But where does that 1.5 come from? Prior to my PR the blame points to:
https://github.com/napari-threedee/napari-threedee/pull/60

**Comment by psobolewskiPhD** [comment]
Kinda feels like this should become `(handle_sizes ) / 2` -- if i understand correctly, why wouldn't the edge also be part of the click/drag target?

**Comment by kevinyamauchi** [comment]
😬 I think this was basically a widget parameter to make it "feel right" during testing. 

>  if i understand correctly, why wouldn't the edge also be part of the click/drag target?

If there is a visible edge, yes. If I recall correctly, when we originally wrote this, we didn't have edges, which in napari is achieved by having an edge that is transparent. Thus we wanted to remove it from the target. Now that we are using the spherical rendering and there have been some changes to the point visual, I'm not sure. 

> Kinda feels like this should become (handle_sizes ) / 2

I think this is worth trying!

**Comment by psobolewskiPhD** [comment]
I think there is also something else going on with the handle sizes.
It's not set in the same coordinates as the manipulator radius.
There can also be the confounder of macOS openGL driver marker size limitations.
