### ISSUE TITLE
Initial workflow ideas

### ISSUE THREAD

**Issue by kevinyamauchi** [napari-threedee/napari-threedee#2]
In this issue, we discuss the initial workflows we aim to add:

## Draw points on a plane in 3D
Have a controllable plane displayed in the volume. The user clicks to add points that get put on the point the cursor ray intersects the plane.

## Draw a line and rotate a rendering plane around the line
Define a line by drawing two points on a plane. Add a render a plane that the line lies on and allow the user to rotate the plane around that line.

## Define a spline with points and translate a rendering plane along the spline
Add points in 3D. Then fit a spline to those points. Add a rendering plane that is on the spline with its normal along the tangent of the spline. Allow the user to slice along the spline using a slider.

**Comment by kevinyamauchi** [comment]
@alisterburt , I think we can close this once #64 merges. Amazing how far we've come!

**Comment by alisterburt** [comment]
agreed! Really fun to see :)
