### ISSUE TITLE
[Docs] How to 1: use render plane manipulator, no sample menu

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#205]
Here's the rendered page:
https://napari-threedee.github.io/how_to/render_plane_manipulator/

- **no sample menu, so can’t use the data shown**
- small visual difference (square end of translator, size) in the look of the manipulator, but copy is all correct

**Comment by psobolewskiPhD** [comment]
Options:
- replace with a built-in napari sample file
- find the "HIV virus-like particles tomogram" and add it as a sample to the plugin
- replace the whole example with one using the example script: https://napari-threedee.github.io/generated/gallery/library/render_plane_manipulator_library/

**Comment by kevinyamauchi** [comment]
Good catch!

Perhaps we can say to install this plugin: https://github.com/teamtomo/cryo-et-sample-data

I think it contains that dataset. Otherwise, the data are available here and we could pretty easily make a sample data plugin: https://zenodo.org/records/6504891

**Comment by psobolewskiPhD** [comment]
On zulip we discussed that adding the sample contribution would be the preferred way to go here, just in terms of the user experience, vs. installing other plugins, etc. But the fallback would be to recommend the plugin and then suggest using a napari sample as fallback.

**Comment by kevinyamauchi** [comment]
@psobolewskiPhD , I have added the sample data plugin in #217. I cut a release and it should be available on pypi in a few minutes.

**Comment by kevinyamauchi** [comment]
> Nice! >400 Mb so definitely will want a warning in the copy. Looks great though, much nicer than the downsample 😄

totally agree!
