### ISSUE TITLE
[Docs] How to 5: annotate spheres, extra layers in viewer

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari-threedee/napari-threedee#209]
Rendered docs:
https://napari-threedee.github.io/how_to/sphere_annotator/

- “open the example” — not sure this is clear. Download the script and run using python script.py
- no link to example, should be https://napari-threedee.github.io/generated/gallery/plugin/sphere_annotator_plugin/
- file name missing `_plugin`
- **there is 1 extra layer after running the script plus Points layer has different name** (note the library script won’t use the widget, so it’s not quite right either and it has spheres present already)
- nr 4, alt click on plane after activate gave a blue point, like in video, so text isn’t quite clear
- r mode and increasing the radius worked perfectly and then it’s clearly a sphere
- n mode worked perfectly, as in the video

**Comment by psobolewskiPhD** [comment]
Simple fix here is to remove the extra plane from the script and rename the layer to match the images/video. Everything else is small edits to the copy.

**Comment by kevinyamauchi** [comment]
> Simple fix here is to remove the extra plane from the script and rename the layer to match the images/video. Everything else is small edits to the copy.

Makes sense to me! I don't think the second plane adds much to the example.

**Comment by psobolewskiPhD** [comment]
The layers are default names from the widget, so can't rename them easily. I think I'll just say the layer names may differ.
