### ISSUE TITLE
Dipole annotator data model plan 

### ISSUE THREAD

**Issue by aysecanuenal** [napari-threedee/napari-threedee#243]
**Data model:**
**One dipole (as an n3d model):** 
- coordinates of the dipole as 3D array (center point)
- direction of the dipole as a 3D array (calculated from the second point)

**Multiple dipoles:**
- List of the single dipole models

---
**Napari layer data model:**
- Points layer: center points as points, directions as features
- Vectors layer: calculated vectors from points and directions

**Comment by alisterburt** [comment]
data model implementation completed in #244
