### ISSUE TITLE
Add a dipole annotator

### ISSUE THREAD

**Issue by alisterburt** [napari-threedee/napari-threedee#247]
Adding a dipole annotator should be a lot easier thanks to @aysecanuenal's fantastic work on the data model in #244 

At it's core this should probably look similar to the existing sphere annotator, so we can take inspiration from there
https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L26

I'll point out a few specific things in the implementation that I think are worth understanding/thinking about...

---

## modes
The annotator has two modes, 'add' and 'edit'. This enum defines the two possible states.
https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L21-L23

An instance of this Enum is stored on the object under an `annotator.mode` property. We use this as the [single source of truth](https://en.wikipedia.org/wiki/Single_source_of_truth) for the 'mode' we are currently in when annotating. When we set the mode property we also make sure the layer will do what we want when we next add a point by making sure the correct point is selected and the values which will be added to the layer features are correct

https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L83-L100

---

## what happens in the add and edit modes?
In add mode, alt + click will add a new point to the points layer then switch to edit mode. 
In edit mode, alt + click will replace the currently selected point, 'moving' it

https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L102-L116

With the specific implementation of how the point gets added to the plane implemented here
https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/utils/napari_utils.py#L311-L366

---

## turning the annotator on and off
All callbacks are attached here in the `_on_enable()` method

https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L199-L214

There is a sister method `_on_disable()` which detaches the callbacks

https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L216-L226

These methods allow us to turn the annotator on and off after creating it.

---
## drawing spheres
One interesting callback is `_on_point_data_changed`
https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L206

napari provides an event which fires whenever the data on a points layer is modified (note that this only fires when the data is modified by methods on the napari points layer, not if we do in place mutation of the numpy array)

Whenever the points data changes, the mesh for the spheres is updated and added to the viewer

https://github.com/napari-threedee/napari-threedee/blob/9ca7669660d4c50a7cb366bbb8108efa4d478df9/src/napari_threedee/annotators/spheres/annotator.py#L228-L247

---

@aysecanuenal  let me know if any questions come up as you go through this! If you want to take a crack at putting things together please go ahead - I would start by building some intuition around the sphere annotator, running the example below and setting breakpoints inside the annotator implementation at whatever point you're interested in, stepping through the code and seeing what happens

https://github.com/napari-threedee/napari-threedee/blob/main/docs/examples/library/sphere_annotator_library.py

Once you're happy with that you could try to set up a similar example for the new dipole annotator and debugging your implementation should be the same experience as exploring the sphere annotator 🙂 

No pressure to have anything done before we meet next of course! 

cc @psobolewskiPhD - I remember you were trying to annotate directions in some funky light microscopy data recently?

**Comment by psobolewskiPhD** [comment]
Yes, "anatomical" coordinate systems and then points within them.
I'm quite curious what these dipoles will look like 😄

**Comment by alisterburt** [comment]
@psobolewskiPhD check #248 for a preview of this annotator!

**Comment by alisterburt** [comment]
it sounds like you would actually need a full 3D coordinate system though, not a single vector

**Comment by alisterburt** [comment]
closed by #248 - congratulations to @aysecanuenal !!
