### ISSUE TITLE
Make napari-threedee available on conda-forge

### ISSUE THREAD

**Issue by haesleinhuepf** [napari-threedee/napari-threedee#66]
Hi all,

I would love to ship napari-threedee together with of devbio-napari. This should just work, the only thing is: It would be cool if it was available via conda-forge.

See also:
* [ ] https://github.com/haesleinhuepf/devbio-napari/issues/29

**Comment by alisterburt** [comment]
Nice! I'm on board with releasing to conda-forge and will add it to a list of things to do before the next release

**Comment by kevinyamauchi** [comment]
Agreed!

**Comment by kevinyamauchi** [comment]
FYI, @haesleinhuepf , the recipe has been submitted, so `napari-threedee` should be available on `conda-forge` as soon as the team reviews it. One note that @alisterburt and I are preparing our `0.0.2` release now, so there will be some major updates in the next week or two (i.e., maybe don't depend on `napari-threedee` too heavily yet).

https://github.com/conda-forge/staged-recipes/pull/20836

**Comment by haesleinhuepf** [comment]
Awesome thanks for letting me know! I presume, I'll start using it more not before December anyway 😉

**Comment by kevinyamauchi** [comment]
Recipe was approved!

https://github.com/conda-forge/napari-threedee-feedstock

**Comment by haesleinhuepf** [comment]
Woohoo 🎉 that was fast. Thanks everyone! 🙌
