### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by kevinyamauchi** [napari-threedee/napari-threedee#69]
There were a couple of CameraSpline tests that were failing on Windows in #64. I skipped them for now, but we should circle back and fix those.

**Comment by psobolewskiPhD** [comment]
That was fixed in https://github.com/napari-threedee/napari-threedee/pull/95 and is no longer skipped, so this can be closed @kevinyamauchi 
🎉

**Comment by kevinyamauchi** [comment]
Woo! Thanks @psobolewskiPhD !
