### ISSUE TITLE
Examples gallery for the docs

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari-threedee/napari-threedee#99]
Currently, there are a lot of great [examples](https://github.com/napari-threedee/napari-threedee/tree/main/examples) that are effectively invisible to new users [looking at the documentation page](https://napari-threedee.github.io/).

We should find a way to automatically display these examples in the docs. Ideally the example scripts would also be executed, and a screenshot of the viewer/output displayed.

**Comment by GenevieveBuckley** [comment]
I've done some work on this already, here's a summary:

1. A [mkdocs-gallery](https://smarie.github.io/mkdocs-gallery/) plugin exists, which does most of what we want. We could use this as-is today to automatically show the example scripts in the docs (but not execute them or show screenshots, because there is extra difficulty involved in managing the napari qt window cleanup)
2. One odd thing I've noticed is that although the mkdocs-gallery README says you can have your examples folder either inside `docs/` or sitting up at the same level... in practice I've found that I get an error if the `examples/` and `docs/` folders are side by side on the same level. This is annoying, but in the worst case scenario we can just rearrange the examples folder to live under `docs/examples/` if we have to.
3. I've been working on extending mkdocs-gallery to support qt and napari application windows. Then we can execute the scripts and show screenshots of the output. I'm pretty close!

**Comment by GenevieveBuckley** [comment]
Here's some screenshots of my work-in-progress mkdocs-gallery support for napari & qt windows:

![Screen Shot 2023-03-17 at 5 04 29 pm](https://user-images.githubusercontent.com/30920819/225828390-2b774bd3-f304-494b-9d62-8b1ff8415f64.png)
![Screen Shot 2023-03-17 at 5 21 05 pm](https://user-images.githubusercontent.com/30920819/225828421-4988238a-3b53-46eb-8551-0fe546df626f.png)
![Screen Shot 2023-03-17 at 5 21 16 pm](https://user-images.githubusercontent.com/30920819/225828442-bb22418f-2f95-4343-981d-892bd25e5e26.png)

**Comment by GenevieveBuckley** [comment]
Annoying things so far:
* As I said above, I'm getting an error when the examples folder and the docs folder are side by side (but it works well when the examples are nested within the docs folder).
* There are a lot of warnings output whenever I open a napari viewer, and that output is being captured and displayed by `mkdocs-gallery`. I'd like to suppress that unwanted output somehow, or get rid of the warnings from napari altogether.
* Finally, I can do multiple napari screenshots provided that the viewers are in separate cells (`# %%` comment lines are used to separate a regular script into multiple notebook "cells").
    * There's no good way to know how many napari viewers currently exist (there is a nice easy way to get the current viewer - thanks Alister!).
    * But even when I set a while loop (eg: `while napari.get_current_viewer() is not None:`) there is still something wrong. I'm not sure what it is or how to fix it yet. Worst case scenario, we'll just have to make sure every viewer is separated by the `# %%` cell comment lines to avoid this problem and be safe.

**Comment by kevinyamauchi** [comment]
Wow, this is super cool, @GenevieveBuckley ! I totally agree that our examples are not very discoverable. 

> As I said above, I'm getting an error when the examples folder and the docs folder are side by side (but it works well when the examples are nested within the docs folder).

do you think copy the `napari-threedee/examples` folder to `napari-threedee/docs/examples` on CI after a merge to main is sufficient for keeping the nested-in-docs example folder in sync? I understand duplication isn't ideal, but maybe a one-way copy would be okay?

> But even when I set a while loop (eg: while napari.get_current_viewer() is not None:) there is still something wrong. I'm not sure what it is or how to fix it yet. Worst case scenario, we'll just have to make sure every viewer is separated by the # %% cell comment lines to avoid this problem and be safe.

Personally, I would be okay with the `# %%` solution as a way to get unblocked and then looping back to figure it out later.

**Comment by GenevieveBuckley** [comment]
>>  As I said above, I'm getting an error when the examples folder and the docs folder are side by side (but it works well when the examples are nested within the docs folder).
>
> do you think copy the `napari-threedee/examples` folder to `napari-threedee/docs/examples` on CI after a merge to main is sufficient for keeping the nested-in-docs example folder in sync? I understand duplication isn't ideal, but maybe a one-way copy would be okay?

Why not just move the examples folder? 

imo, it's not a good idea to have a complicated solution relying on automated scripts to copy things around. Situations like that are hard to debug if they don't work the way they should, and people often forget that they're doing things.

I've opened an issue about this, but I don't think we should rely on the situation changing anytime soon. https://github.com/smarie/mkdocs-gallery/issues/54

**Comment by GenevieveBuckley** [comment]
>>     Worst case scenario, we'll just have to make sure every viewer is separated by the # %% cell comment lines to avoid this problem and be safe.
>
> Personally, I would be okay with the # %% solution as a way to get unblocked and then looping back to figure it out later.

I've opened a PR in napari that would help: https://github.com/napari/napari/pull/5664
